// Copyright 2021 Miron Krivosheev
#ifndef MODULES_TASK_3_KRIVOSHEEV_M_TRAPEZIUM_INTEGRAL_H_
#define MODULES_TASK_3_KRIVOSHEEV_M_TRAPEZIUM_INTEGRAL_H_

#include <string>


#endif  // MODULES_TASK_3_KRIVOSHEEV_M_TRAPEZIUM_INTEGRAL_H_
