// Copyright 2021 Kharunova Alina
#ifndef MODULES_TASK_2_KHARUNOVA_A_PRODUCER_CONSUMER_PRODUCER_CONSUMER_H_
#define MODULES_TASK_2_KHARUNOVA_A_PRODUCER_CONSUMER_PRODUCER_CONSUMER_H_

int process(int enterings);

void producer();

void consumer();

void waiting();

#endif  // MODULES_TASK_2_KHARUNOVA_A_PRODUCER_CONSUMER_PRODUCER_CONSUMER_H_
