// Copyright 2021 Krapivenskikh Stepan
#ifndef MODULES_TASK_2_KRAPIVENSKIKH_S_STAR_TOPOLOGY_STAR_TOPOLOGY_H_
#define MODULES_TASK_2_KRAPIVENSKIKH_S_STAR_TOPOLOGY_STAR_TOPOLOGY_H_

#include <mpi.h>

MPI_Comm createStarTopology();

#endif  // MODULES_TASK_2_KRAPIVENSKIKH_S_STAR_TOPOLOGY_STAR_TOPOLOGY_H_
