// Copyright 2021 Podovinnikov Artyom
#ifndef MODULES_TASK_3_PODOVINNIKOV_A_STRONGIN_GLOBAL_SEARCH_STRONGIN_GLOBAL_SEARCH_H_
#define MODULES_TASK_3_PODOVINNIKOV_A_STRONGIN_GLOBAL_SEARCH_STRONGIN_GLOBAL_SEARCH_H_

double MPI_Strongin(double a, double b, double (*Q)(double));

#endif  // MODULES_TASK_3_PODOVINNIKOV_A_STRONGIN_GLOBAL_SEARCH_STRONGIN_GLOBAL_SEARCH_H_
